# Generated by Django 6.0.4 on 2026-04-12 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField(unique=True)),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=15)),
                ('emp_phn', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile must be 10 digits long', regex='^[6-9]\\d{9}$')])),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_date_of_join', models.DateField(blank=True, null=True)),
                ('emp_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(unique=True)),
                ('stu_name', models.CharField(max_length=15)),
                ('stu_age', models.IntegerField()),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_class', models.IntegerField()),
                ('stu_marks', models.IntegerField()),
                ('stu_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
    ]
